spring:
  application:
    name: automatic-okr
  data:
    mongodb:
      uri: "mongodb://localhost:27017"
      name: "automatic-okr"
server.port: 8282
jira:
  url: "https://barakyedaya.atlassian.net"
  username: "barak.yedaya@gmail.com"
  project-uri: "/rest/api/2/project/"
  apiToken: ${{ secrets.JIRA_API_TOKEN }}
  role-uri: "/rest/api/2/project/{ID}/role"
openai:
  url: "https://api.openai.com//v1/chat/completions"
  token: ${{ secrets.OPENAI_TOKEN }}
  gpt-3.5-turbo-0125: "gpt-3.5-turbo-0125"
  gpt-4: "gpt-4"
  system-content-get-okr: "When I am sending you an objective, you will reply with a list of key results that are corresponding to that objective.\""
  system-content-nested-organization-with-okrs: "when I give you a hierarchical JSON structure of a company and an objective for that company, you will reply with the same JSON structure while filling in the \"okrs\" field structure in each level. \nthe \"okrs\" field structure is the following:\n\n\"okrs\": [\n\t\t\t\t{\n\t\t\t\t\t\"objective\": null,\n\t\t\t\t\t\"derivedFromKeyResultId\": null,\n\t\t\t\t\t\"keyResults\": [\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\"keyResult\": null,\n\t\t\t\t\t\t\t\"keyResultId\": null\n\t\t\t\t\t\t}\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t]\n\nalthough this structure has only one \"keyResult\" in the \"keyResults\" list, you can have multiple \"keyResult\" if you see the need. for the lower levels, although this structure has only one \"objective\" in it, you can have multiple objectives if you see the need. the \"objective\" of the highest level is the only field that shouldn't be deleted. you will do that in the following way:\n1. \"objective\": the objective of each level which is derived from a higher level key result.\n2. \"derivedFromKeyResultId\": the higher level key result ID this objective is derived from\n3. \"keyResults\": the key results that are corresponding to that objective\n4. \"keyResult\": a key result that is corresponding to that objective\n5. \"keyResultId\": the ID of the key result"